### ISSUE TITLE
Further explain the protocol (pieces are missing)

### ISSUE THREAD

**Issue by marcofranssen** [socketio/socket.io-protocol#12]
The protocol is not very clear on how it exactly works.
As Example this issue. https://github.com/Automattic/socket.io/issues/1894

Nowhere is described that upgrading the connection needs a 5 to be sent over the websocket to complete it before other messages are sent.

connecting to a namespace requires a 40.

However that number is not explained over here.

4 means error
0 means connect

**Comment by daid** [comment]
Actually, I think this document is an insult to actual protocol descriptions. As it reads like some odd document which cannot decide if it's a protocol description or an API documentation.

**Comment by Grant1219** [comment]
Yea I agree with daid... your best bet is probably installing the node.js server and the example programs, then using tcpdump or another sniffer to analyze the protocol. That's what I'm trying to do at the moment anyway.

**Comment by thetrompf** [comment]
The 4 comes from then engine.io-protocol, so when looking on the raw data send over the wire, it goes through two "protocols" the raw transportation layer (engine.io-protocol) and then the specific transport layer, in this case socket.io-protocol, so 40 means 4 (message from the engine.io-protocol) and 0 which meanse connnect, and then the rest is the `/nsp` part.

**Comment by rauchg** [comment]
I'm closing this in favor of #14, let's continue the discussion there.
