### ISSUE TITLE
How can one understand this spec?

### ISSUE THREAD

**Issue by Injac** [socketio/socket.io-protocol#13]
I have difficulties in even understanding the notation of the protocol specification. Is that intended? If you want people to adapt the protocol to different platforms, a real specification would be very helpful. Even an RFC is easier to read than what you have here. I don't expect an answer at all, because I see that this issue is not a big concern for the socket.io implementers. If so, it would be reflected in a better documentation.
I think reverse-engineering  of the protocol will be less error-prone than the docs. Hope to see some changes soon.

**Comment by shuoli84** [comment]
The only doc meaningful for socketio is its js implementation. +1


发自我的 iPhone

**Comment by mrniko** [comment]
@shuoli84 +1

**Comment by rauchg** [comment]
@lnjac @shuoli84 @mrniko we're working on a proper RFC. This was more of an informal / quick guide that we wrote while implementing the JS parsers. I appreciate the feedback.

**Comment by rauchg** [comment]
Btw, if you have examples of what your ideal specifications would be, please post them here.

**Comment by rauchg** [comment]
I'm closing this in favor of #14, let's continue the discussion there.
