### ISSUE TITLE
socket.io unity authentication

### ISSUE THREAD

**Issue by mahdiyaroraei** [socketio/socket.io-protocol#17]
Can you explain what is your solution for user authentication over socket.io?

**Comment by darrachequesne** [comment]
[Middlewares](https://socket.io/docs/namespaces/#Namespace-middleware) may be used for user authentication:

- you can either reuse existing Express middlewares, like [Passport.js](http://www.passportjs.org/) (example [here](https://github.com/socketio/socket.io/tree/master/examples/passport-example))

- or provide your own middleware

Client

```js
const io = require("socket.io-client");
const socket = io({
  query: {
    token: "abcd"
  }
});
socket.on("connect", () => { /* success */ });
socket.on("error", () => { /* failure */ });
```

Server
```js
const io = require("socket.io");
io.use((socket, next) => {
  if (socket.handshake.query.token === "abcd") {
    next();
  } else {
    next(new Error('invalid'));
  }
});
io.on('connect', socket => {});
```
