### ISSUE TITLE
What do 420, 421, 422, 423, 424, 425 mean? And what protocol version?

### ISSUE THREAD

**Issue by coolaj86** [socketio/socket.io-protocol#27]
I'm trying to communicate with an `EIO=3` socket.io server and I'm noticing that there's this 42x number showing up in front of the subscriptions after the length:

```txt
POST https://insight.dash.org/socket.io/?EIO=3&transport=polling&t=O5WgT6e&sid=vsxjXIoH1XiRiBLwBdSW

22:423["subscribe","inv"]23:424["subscribe","sync"]75:420["subscribe","dashd/addresstxid",["XoQVXRCQ6rR9s2EKh5GDMXR3JRtKCzt9pp"]]23:421["subscribe","sync"]23:425["subscribe","sync"]
```

For the life of me, I cannot figure out what this is supposed to mean, and I can't seem to find any documentation referencing this protocol version, nor can I find this pattern in the current versions of reference implementations that I've looked at.

It seems like the 42x number rotates, but not in any order I can understand.

I'd love some help deciphering what's going on here.

**Comment by darrachequesne** [comment]
I think this can be closed now, please reopen if needed.

**Comment by coolaj86** [comment]
Yes.

I didn't see the notification about the answer at the time, but thank you so much @darrachequesne for such a great explanation.

I'm pretty sure I'll need to reference this again in the future, so I'm glad to have it.
