### ISSUE TITLE
Sample conversation packets?

### ISSUE THREAD

**Issue by Xeoncross** [socketio/socket.io-protocol#9]
To help illustrate the protocol can you update the readme with a snippet of packets that represents a successful connection to the server and send?

```
CONNECT
ACK
{"sid":"YasdL-sPEI9Ii5EzAAeq","upgrades":[],"pingInterval":25000,"pingTimeout":60000}
....
```

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-protocol/commit/bce66e82963505631168d318c79d55d74077dac8.
